// Models TypeScript files should be AUTO-GENERATED by the Typewriter Visual Studio plugin. Do not modify this file.
// @ts-ignore
import * as moment from 'moment';
import InterfaceConstructor from './InterfaceConstructor';

interface TableRequestFilterDTO { 
    columnProp: string | null;
    filter: string | null;
}
const TableRequestFilterDTO: InterfaceConstructor<TableRequestFilterDTO> = {
    create: (initValues?: {} | null | undefined) => {
        return Object.assign(
        {
            columnProp: null,
            filter: null,
        },
        initValues);
    }
};

export default TableRequestFilterDTO;
